// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MMOPPPMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.MMOPPP.Messages {

  /// <summary>Holder for reflection information generated from MMOPPPMessages.proto</summary>
  public static partial class MMOPPPMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for MMOPPPMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MMOPPPMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNTU9QUFBNZXNzYWdlcy5wcm90bxIGTU1PUFBQGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIioKB1ZlY3RvcjMSCQoBeBgBIAEoAhIJCgF5",
            "GAIgASgCEgkKAXoYAyABKAIiKAoKSWRlbnRpZmllchIMCgRuYW1lGAEgASgJ",
            "EgwKBHRhZ3MYAiABKAkigQEKC0VudGl0eUlucHV0EikKEGRpcmVjdGlvbl9p",
            "bnB1dHMYAyABKAsyDy5NTU9QUFAuVmVjdG9yMxInCg5ldWxlcl9yb3RhdGlv",
            "bhgEIAEoCzIPLk1NT1BQUC5WZWN0b3IzEg4KBnN0cmFmZRgFIAEoCBIOCgZz",
            "cHJpbnQYBiABKAgigQEKDEVudGl0eVVwZGF0ZRIeCgJpZBgBIAEoCzISLk1N",
            "T1BQUC5JZGVudGlmaWVyEi4KEXByZWRpY3RpdmVfaW5wdXRzGAIgASgLMhMu",
            "TU1PUFBQLkVudGl0eUlucHV0EiEKCHBvc2l0aW9uGAMgASgLMg8uTU1PUFBQ",
            "LlZlY3RvcjMiNAoLV29ybGRVcGRhdGUSJQoHdXBkYXRlcxgBIAMoCzIULk1N",
            "T1BQUC5FbnRpdHlVcGRhdGUihQEKC1BsYXllcklucHV0Eh4KAmlkGAEgASgL",
            "MhIuTU1PUFBQLklkZW50aWZpZXISJwoKbW92ZV9pbnB1dBgCIAEoCzITLk1N",
            "T1BQUC5FbnRpdHlJbnB1dBItCglzZW50X3RpbWUYDyABKAsyGi5nb29nbGUu",
            "cHJvdG9idWYuVGltZXN0YW1wQiKqAh9Hb29nbGUuUHJvdG9idWYuTU1PUFBQ",
            "Lk1lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.Vector3), global::Google.Protobuf.MMOPPP.Messages.Vector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.Identifier), global::Google.Protobuf.MMOPPP.Messages.Identifier.Parser, new[]{ "Name", "Tags" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.EntityInput), global::Google.Protobuf.MMOPPP.Messages.EntityInput.Parser, new[]{ "DirectionInputs", "EulerRotation", "Strafe", "Sprint" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.EntityUpdate), global::Google.Protobuf.MMOPPP.Messages.EntityUpdate.Parser, new[]{ "Id", "PredictiveInputs", "Position" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.WorldUpdate), global::Google.Protobuf.MMOPPP.Messages.WorldUpdate.Parser, new[]{ "Updates" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.PlayerInput), global::Google.Protobuf.MMOPPP.Messages.PlayerInput.Parser, new[]{ "Id", "MoveInput", "SentTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// -- Helper Messages --
  /// </summary>
  public sealed partial class Vector3 : pb::IMessage<Vector3> {
    private static readonly pb::MessageParser<Vector3> _parser = new pb::MessageParser<Vector3>(() => new Vector3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vector3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3(Vector3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3 Clone() {
      return new Vector3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    /// <summary>
    /// Forward
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    /// <summary>
    /// Right
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    /// <summary>
    /// Up
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Vector3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vector3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vector3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Identifier : pb::IMessage<Identifier> {
    private static readonly pb::MessageParser<Identifier> _parser = new pb::MessageParser<Identifier>(() => new Identifier());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Identifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identifier(Identifier other) : this() {
      name_ = other.name_;
      tags_ = other.tags_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identifier Clone() {
      return new Identifier(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 2;
    private string tags_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Tags {
      get { return tags_; }
      set {
        tags_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Identifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Identifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Tags != other.Tags) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Tags.Length != 0) hash ^= Tags.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Tags.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Tags);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Tags.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tags);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Identifier other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Tags.Length != 0) {
        Tags = other.Tags;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Tags = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EntityInput : pb::IMessage<EntityInput> {
    private static readonly pb::MessageParser<EntityInput> _parser = new pb::MessageParser<EntityInput>(() => new EntityInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityInput(EntityInput other) : this() {
      directionInputs_ = other.directionInputs_ != null ? other.directionInputs_.Clone() : null;
      eulerRotation_ = other.eulerRotation_ != null ? other.eulerRotation_.Clone() : null;
      strafe_ = other.strafe_;
      sprint_ = other.sprint_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityInput Clone() {
      return new EntityInput(this);
    }

    /// <summary>Field number for the "direction_inputs" field.</summary>
    public const int DirectionInputsFieldNumber = 3;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 directionInputs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 DirectionInputs {
      get { return directionInputs_; }
      set {
        directionInputs_ = value;
      }
    }

    /// <summary>Field number for the "euler_rotation" field.</summary>
    public const int EulerRotationFieldNumber = 4;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 eulerRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 EulerRotation {
      get { return eulerRotation_; }
      set {
        eulerRotation_ = value;
      }
    }

    /// <summary>Field number for the "strafe" field.</summary>
    public const int StrafeFieldNumber = 5;
    private bool strafe_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Strafe {
      get { return strafe_; }
      set {
        strafe_ = value;
      }
    }

    /// <summary>Field number for the "sprint" field.</summary>
    public const int SprintFieldNumber = 6;
    private bool sprint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sprint {
      get { return sprint_; }
      set {
        sprint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DirectionInputs, other.DirectionInputs)) return false;
      if (!object.Equals(EulerRotation, other.EulerRotation)) return false;
      if (Strafe != other.Strafe) return false;
      if (Sprint != other.Sprint) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (directionInputs_ != null) hash ^= DirectionInputs.GetHashCode();
      if (eulerRotation_ != null) hash ^= EulerRotation.GetHashCode();
      if (Strafe != false) hash ^= Strafe.GetHashCode();
      if (Sprint != false) hash ^= Sprint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (directionInputs_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DirectionInputs);
      }
      if (eulerRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EulerRotation);
      }
      if (Strafe != false) {
        output.WriteRawTag(40);
        output.WriteBool(Strafe);
      }
      if (Sprint != false) {
        output.WriteRawTag(48);
        output.WriteBool(Sprint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (directionInputs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DirectionInputs);
      }
      if (eulerRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EulerRotation);
      }
      if (Strafe != false) {
        size += 1 + 1;
      }
      if (Sprint != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityInput other) {
      if (other == null) {
        return;
      }
      if (other.directionInputs_ != null) {
        if (directionInputs_ == null) {
          DirectionInputs = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        DirectionInputs.MergeFrom(other.DirectionInputs);
      }
      if (other.eulerRotation_ != null) {
        if (eulerRotation_ == null) {
          EulerRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        EulerRotation.MergeFrom(other.EulerRotation);
      }
      if (other.Strafe != false) {
        Strafe = other.Strafe;
      }
      if (other.Sprint != false) {
        Sprint = other.Sprint;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            if (directionInputs_ == null) {
              DirectionInputs = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(DirectionInputs);
            break;
          }
          case 34: {
            if (eulerRotation_ == null) {
              EulerRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(EulerRotation);
            break;
          }
          case 40: {
            Strafe = input.ReadBool();
            break;
          }
          case 48: {
            Sprint = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// From Server
  /// </summary>
  public sealed partial class EntityUpdate : pb::IMessage<EntityUpdate> {
    private static readonly pb::MessageParser<EntityUpdate> _parser = new pb::MessageParser<EntityUpdate>(() => new EntityUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUpdate(EntityUpdate other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      predictiveInputs_ = other.predictiveInputs_ != null ? other.predictiveInputs_.Clone() : null;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUpdate Clone() {
      return new EntityUpdate(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Google.Protobuf.MMOPPP.Messages.Identifier id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Identifier Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "predictive_inputs" field.</summary>
    public const int PredictiveInputsFieldNumber = 2;
    private global::Google.Protobuf.MMOPPP.Messages.EntityInput predictiveInputs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.EntityInput PredictiveInputs {
      get { return predictiveInputs_; }
      set {
        predictiveInputs_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(PredictiveInputs, other.PredictiveInputs)) return false;
      if (!object.Equals(Position, other.Position)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (predictiveInputs_ != null) hash ^= PredictiveInputs.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (predictiveInputs_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PredictiveInputs);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (predictiveInputs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PredictiveInputs);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityUpdate other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Google.Protobuf.MMOPPP.Messages.Identifier();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.predictiveInputs_ != null) {
        if (predictiveInputs_ == null) {
          PredictiveInputs = new global::Google.Protobuf.MMOPPP.Messages.EntityInput();
        }
        PredictiveInputs.MergeFrom(other.PredictiveInputs);
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        Position.MergeFrom(other.Position);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Google.Protobuf.MMOPPP.Messages.Identifier();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            if (predictiveInputs_ == null) {
              PredictiveInputs = new global::Google.Protobuf.MMOPPP.Messages.EntityInput();
            }
            input.ReadMessage(PredictiveInputs);
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    }

  }

  public sealed partial class WorldUpdate : pb::IMessage<WorldUpdate> {
    private static readonly pb::MessageParser<WorldUpdate> _parser = new pb::MessageParser<WorldUpdate>(() => new WorldUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WorldUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldUpdate(WorldUpdate other) : this() {
      updates_ = other.updates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldUpdate Clone() {
      return new WorldUpdate(this);
    }

    /// <summary>Field number for the "updates" field.</summary>
    public const int UpdatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Protobuf.MMOPPP.Messages.EntityUpdate> _repeated_updates_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Protobuf.MMOPPP.Messages.EntityUpdate.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.EntityUpdate> updates_ = new pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.EntityUpdate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.EntityUpdate> Updates {
      get { return updates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WorldUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WorldUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updates_.Equals(other.updates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      updates_.WriteTo(output, _repeated_updates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += updates_.CalculateSize(_repeated_updates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WorldUpdate other) {
      if (other == null) {
        return;
      }
      updates_.Add(other.updates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updates_.AddEntriesFrom(input, _repeated_updates_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// To Server
  /// </summary>
  public sealed partial class PlayerInput : pb::IMessage<PlayerInput> {
    private static readonly pb::MessageParser<PlayerInput> _parser = new pb::MessageParser<PlayerInput>(() => new PlayerInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerInput(PlayerInput other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      moveInput_ = other.moveInput_ != null ? other.moveInput_.Clone() : null;
      sentTime_ = other.sentTime_ != null ? other.sentTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerInput Clone() {
      return new PlayerInput(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Google.Protobuf.MMOPPP.Messages.Identifier id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Identifier Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "move_input" field.</summary>
    public const int MoveInputFieldNumber = 2;
    private global::Google.Protobuf.MMOPPP.Messages.EntityInput moveInput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.EntityInput MoveInput {
      get { return moveInput_; }
      set {
        moveInput_ = value;
      }
    }

    /// <summary>Field number for the "sent_time" field.</summary>
    public const int SentTimeFieldNumber = 15;
    private global::Google.Protobuf.WellKnownTypes.Timestamp sentTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SentTime {
      get { return sentTime_; }
      set {
        sentTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(MoveInput, other.MoveInput)) return false;
      if (!object.Equals(SentTime, other.SentTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (moveInput_ != null) hash ^= MoveInput.GetHashCode();
      if (sentTime_ != null) hash ^= SentTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (moveInput_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MoveInput);
      }
      if (sentTime_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(SentTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (moveInput_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MoveInput);
      }
      if (sentTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SentTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerInput other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Google.Protobuf.MMOPPP.Messages.Identifier();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.moveInput_ != null) {
        if (moveInput_ == null) {
          MoveInput = new global::Google.Protobuf.MMOPPP.Messages.EntityInput();
        }
        MoveInput.MergeFrom(other.MoveInput);
      }
      if (other.sentTime_ != null) {
        if (sentTime_ == null) {
          SentTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SentTime.MergeFrom(other.SentTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Google.Protobuf.MMOPPP.Messages.Identifier();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            if (moveInput_ == null) {
              MoveInput = new global::Google.Protobuf.MMOPPP.Messages.EntityInput();
            }
            input.ReadMessage(MoveInput);
            break;
          }
          case 122: {
            if (sentTime_ == null) {
              SentTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SentTime);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
