// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MMOPPPMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.MMOPPP.Messages {

  /// <summary>Holder for reflection information generated from MMOPPPMessages.proto</summary>
  public static partial class MMOPPPMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for MMOPPPMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MMOPPPMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNTU9QUFBNZXNzYWdlcy5wcm90bxIGTU1PUFBQGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIioKB1ZlY3RvcjMSCQoBeBgBIAEoAhIJCgF5",
            "GAIgASgCEgkKAXoYAyABKAIi4QEKBUlucHV0EisKEnBsYXllcl9tb3ZlX2lu",
            "cHV0cxgDIAEoCzIPLk1NT1BQUC5WZWN0b3IzEiwKE2V1bGVyX2JvZHlfcm90",
            "YXRpb24YBCABKAsyDy5NTU9QUFAuVmVjdG9yMxIuChVldWxlcl9jYW1lcmFf",
            "cm90YXRpb24YBSABKAsyDy5NTU9QUFAuVmVjdG9yMxIOCgZzdHJhZmUYBiAB",
            "KAgSDgoGc3ByaW50GAcgASgIEi0KCXNlbnRfdGltZRgIIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXAiiwEKDFNlcnZlclVwZGF0ZRIMCgRuYW1l",
            "GAEgASgJEiIKC3Bhc3RfaW5wdXRzGAIgAygLMg0uTU1PUFBQLklucHV0EiEK",
            "CGxvY2F0aW9uGAMgASgLMg8uTU1PUFBQLlZlY3RvcjMSJgoNYm9keV9yb3Rh",
            "dGlvbhgEIAEoCzIPLk1NT1BQUC5WZWN0b3IzIjYKDVNlcnZlclVwZGF0ZXMS",
            "JQoHdXBkYXRlcxgBIAMoCzIULk1NT1BQUC5TZXJ2ZXJVcGRhdGUiOQoLQ2xp",
            "ZW50SW5wdXQSDAoEbmFtZRgBIAEoCRIcCgVpbnB1dBgCIAEoCzINLk1NT1BQ",
            "UC5JbnB1dEIiqgIfR29vZ2xlLlByb3RvYnVmLk1NT1BQUC5NZXNzYWdlc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.Vector3), global::Google.Protobuf.MMOPPP.Messages.Vector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.Input), global::Google.Protobuf.MMOPPP.Messages.Input.Parser, new[]{ "PlayerMoveInputs", "EulerBodyRotation", "EulerCameraRotation", "Strafe", "Sprint", "SentTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.ServerUpdate), global::Google.Protobuf.MMOPPP.Messages.ServerUpdate.Parser, new[]{ "Name", "PastInputs", "Location", "BodyRotation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.ServerUpdates), global::Google.Protobuf.MMOPPP.Messages.ServerUpdates.Parser, new[]{ "Updates" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.MMOPPP.Messages.ClientInput), global::Google.Protobuf.MMOPPP.Messages.ClientInput.Parser, new[]{ "Name", "Input" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// -- Helper Messages --
  /// </summary>
  public sealed partial class Vector3 : pb::IMessage<Vector3> {
    private static readonly pb::MessageParser<Vector3> _parser = new pb::MessageParser<Vector3>(() => new Vector3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vector3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3(Vector3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3 Clone() {
      return new Vector3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    /// <summary>
    /// Forward
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    /// <summary>
    /// Right
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    /// <summary>
    /// Up
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Vector3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vector3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vector3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Input : pb::IMessage<Input> {
    private static readonly pb::MessageParser<Input> _parser = new pb::MessageParser<Input>(() => new Input());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Input> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Input() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Input(Input other) : this() {
      playerMoveInputs_ = other.playerMoveInputs_ != null ? other.playerMoveInputs_.Clone() : null;
      eulerBodyRotation_ = other.eulerBodyRotation_ != null ? other.eulerBodyRotation_.Clone() : null;
      eulerCameraRotation_ = other.eulerCameraRotation_ != null ? other.eulerCameraRotation_.Clone() : null;
      strafe_ = other.strafe_;
      sprint_ = other.sprint_;
      sentTime_ = other.sentTime_ != null ? other.sentTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Input Clone() {
      return new Input(this);
    }

    /// <summary>Field number for the "player_move_inputs" field.</summary>
    public const int PlayerMoveInputsFieldNumber = 3;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 playerMoveInputs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 PlayerMoveInputs {
      get { return playerMoveInputs_; }
      set {
        playerMoveInputs_ = value;
      }
    }

    /// <summary>Field number for the "euler_body_rotation" field.</summary>
    public const int EulerBodyRotationFieldNumber = 4;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 eulerBodyRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 EulerBodyRotation {
      get { return eulerBodyRotation_; }
      set {
        eulerBodyRotation_ = value;
      }
    }

    /// <summary>Field number for the "euler_camera_rotation" field.</summary>
    public const int EulerCameraRotationFieldNumber = 5;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 eulerCameraRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 EulerCameraRotation {
      get { return eulerCameraRotation_; }
      set {
        eulerCameraRotation_ = value;
      }
    }

    /// <summary>Field number for the "strafe" field.</summary>
    public const int StrafeFieldNumber = 6;
    private bool strafe_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Strafe {
      get { return strafe_; }
      set {
        strafe_ = value;
      }
    }

    /// <summary>Field number for the "sprint" field.</summary>
    public const int SprintFieldNumber = 7;
    private bool sprint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sprint {
      get { return sprint_; }
      set {
        sprint_ = value;
      }
    }

    /// <summary>Field number for the "sent_time" field.</summary>
    public const int SentTimeFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp sentTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SentTime {
      get { return sentTime_; }
      set {
        sentTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Input);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Input other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PlayerMoveInputs, other.PlayerMoveInputs)) return false;
      if (!object.Equals(EulerBodyRotation, other.EulerBodyRotation)) return false;
      if (!object.Equals(EulerCameraRotation, other.EulerCameraRotation)) return false;
      if (Strafe != other.Strafe) return false;
      if (Sprint != other.Sprint) return false;
      if (!object.Equals(SentTime, other.SentTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (playerMoveInputs_ != null) hash ^= PlayerMoveInputs.GetHashCode();
      if (eulerBodyRotation_ != null) hash ^= EulerBodyRotation.GetHashCode();
      if (eulerCameraRotation_ != null) hash ^= EulerCameraRotation.GetHashCode();
      if (Strafe != false) hash ^= Strafe.GetHashCode();
      if (Sprint != false) hash ^= Sprint.GetHashCode();
      if (sentTime_ != null) hash ^= SentTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (playerMoveInputs_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayerMoveInputs);
      }
      if (eulerBodyRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EulerBodyRotation);
      }
      if (eulerCameraRotation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EulerCameraRotation);
      }
      if (Strafe != false) {
        output.WriteRawTag(48);
        output.WriteBool(Strafe);
      }
      if (Sprint != false) {
        output.WriteRawTag(56);
        output.WriteBool(Sprint);
      }
      if (sentTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SentTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (playerMoveInputs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerMoveInputs);
      }
      if (eulerBodyRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EulerBodyRotation);
      }
      if (eulerCameraRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EulerCameraRotation);
      }
      if (Strafe != false) {
        size += 1 + 1;
      }
      if (Sprint != false) {
        size += 1 + 1;
      }
      if (sentTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SentTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Input other) {
      if (other == null) {
        return;
      }
      if (other.playerMoveInputs_ != null) {
        if (playerMoveInputs_ == null) {
          PlayerMoveInputs = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        PlayerMoveInputs.MergeFrom(other.PlayerMoveInputs);
      }
      if (other.eulerBodyRotation_ != null) {
        if (eulerBodyRotation_ == null) {
          EulerBodyRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        EulerBodyRotation.MergeFrom(other.EulerBodyRotation);
      }
      if (other.eulerCameraRotation_ != null) {
        if (eulerCameraRotation_ == null) {
          EulerCameraRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        EulerCameraRotation.MergeFrom(other.EulerCameraRotation);
      }
      if (other.Strafe != false) {
        Strafe = other.Strafe;
      }
      if (other.Sprint != false) {
        Sprint = other.Sprint;
      }
      if (other.sentTime_ != null) {
        if (sentTime_ == null) {
          SentTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SentTime.MergeFrom(other.SentTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            if (playerMoveInputs_ == null) {
              PlayerMoveInputs = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(PlayerMoveInputs);
            break;
          }
          case 34: {
            if (eulerBodyRotation_ == null) {
              EulerBodyRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(EulerBodyRotation);
            break;
          }
          case 42: {
            if (eulerCameraRotation_ == null) {
              EulerCameraRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(EulerCameraRotation);
            break;
          }
          case 48: {
            Strafe = input.ReadBool();
            break;
          }
          case 56: {
            Sprint = input.ReadBool();
            break;
          }
          case 66: {
            if (sentTime_ == null) {
              SentTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SentTime);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// From Server
  /// </summary>
  public sealed partial class ServerUpdate : pb::IMessage<ServerUpdate> {
    private static readonly pb::MessageParser<ServerUpdate> _parser = new pb::MessageParser<ServerUpdate>(() => new ServerUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerUpdate(ServerUpdate other) : this() {
      name_ = other.name_;
      pastInputs_ = other.pastInputs_.Clone();
      location_ = other.location_ != null ? other.location_.Clone() : null;
      bodyRotation_ = other.bodyRotation_ != null ? other.bodyRotation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerUpdate Clone() {
      return new ServerUpdate(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "past_inputs" field.</summary>
    public const int PastInputsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Protobuf.MMOPPP.Messages.Input> _repeated_pastInputs_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Protobuf.MMOPPP.Messages.Input.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.Input> pastInputs_ = new pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.Input>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.Input> PastInputs {
      get { return pastInputs_; }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 3;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 location_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "body_rotation" field.</summary>
    public const int BodyRotationFieldNumber = 4;
    private global::Google.Protobuf.MMOPPP.Messages.Vector3 bodyRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Vector3 BodyRotation {
      get { return bodyRotation_; }
      set {
        bodyRotation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!pastInputs_.Equals(other.pastInputs_)) return false;
      if (!object.Equals(Location, other.Location)) return false;
      if (!object.Equals(BodyRotation, other.BodyRotation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= pastInputs_.GetHashCode();
      if (location_ != null) hash ^= Location.GetHashCode();
      if (bodyRotation_ != null) hash ^= BodyRotation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      pastInputs_.WriteTo(output, _repeated_pastInputs_codec);
      if (location_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Location);
      }
      if (bodyRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BodyRotation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += pastInputs_.CalculateSize(_repeated_pastInputs_codec);
      if (location_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Location);
      }
      if (bodyRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BodyRotation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerUpdate other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      pastInputs_.Add(other.pastInputs_);
      if (other.location_ != null) {
        if (location_ == null) {
          Location = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        Location.MergeFrom(other.Location);
      }
      if (other.bodyRotation_ != null) {
        if (bodyRotation_ == null) {
          BodyRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
        }
        BodyRotation.MergeFrom(other.BodyRotation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            pastInputs_.AddEntriesFrom(input, _repeated_pastInputs_codec);
            break;
          }
          case 26: {
            if (location_ == null) {
              Location = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(Location);
            break;
          }
          case 34: {
            if (bodyRotation_ == null) {
              BodyRotation = new global::Google.Protobuf.MMOPPP.Messages.Vector3();
            }
            input.ReadMessage(BodyRotation);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ServerUpdates : pb::IMessage<ServerUpdates> {
    private static readonly pb::MessageParser<ServerUpdates> _parser = new pb::MessageParser<ServerUpdates>(() => new ServerUpdates());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerUpdates> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerUpdates() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerUpdates(ServerUpdates other) : this() {
      updates_ = other.updates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerUpdates Clone() {
      return new ServerUpdates(this);
    }

    /// <summary>Field number for the "updates" field.</summary>
    public const int UpdatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Protobuf.MMOPPP.Messages.ServerUpdate> _repeated_updates_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Protobuf.MMOPPP.Messages.ServerUpdate.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.ServerUpdate> updates_ = new pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.ServerUpdate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.MMOPPP.Messages.ServerUpdate> Updates {
      get { return updates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerUpdates);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerUpdates other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updates_.Equals(other.updates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      updates_.WriteTo(output, _repeated_updates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += updates_.CalculateSize(_repeated_updates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerUpdates other) {
      if (other == null) {
        return;
      }
      updates_.Add(other.updates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updates_.AddEntriesFrom(input, _repeated_updates_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// To Server
  /// </summary>
  public sealed partial class ClientInput : pb::IMessage<ClientInput> {
    private static readonly pb::MessageParser<ClientInput> _parser = new pb::MessageParser<ClientInput>(() => new ClientInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.MMOPPP.Messages.MMOPPPMessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInput(ClientInput other) : this() {
      name_ = other.name_;
      input_ = other.input_ != null ? other.input_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInput Clone() {
      return new ClientInput(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "input" field.</summary>
    public const int InputFieldNumber = 2;
    private global::Google.Protobuf.MMOPPP.Messages.Input input_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.MMOPPP.Messages.Input Input {
      get { return input_; }
      set {
        input_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Input, other.Input)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (input_ != null) hash ^= Input.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (input_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Input);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (input_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Input);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientInput other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.input_ != null) {
        if (input_ == null) {
          Input = new global::Google.Protobuf.MMOPPP.Messages.Input();
        }
        Input.MergeFrom(other.Input);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (input_ == null) {
              Input = new global::Google.Protobuf.MMOPPP.Messages.Input();
            }
            input.ReadMessage(Input);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
